from . import eagleedu_application
from . import eagleedu_student
from . import eagleedu_instructor
from . import eagleedu_academic_year
from . import eagleedu_class
from . import eagleedu_group_division
from . import eagleedu_assigning_class
from . import eagleedu_class_wizard
from . import eagleedu_class_division
from . import eagleedu_class_section
from . import eagleedu_class_history
from . import eagleedu_subject
from . import eagleedu_syllabus
from . import eagleedu_register
from . import eagleedu_roomname
from . import eagleedu_roomnumber
from . import eagleedu_class_category
from . import eagleedu_guardian_relation
from . import eagleedu_campus
